// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/cart": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/products" | "/cart";
  };
  "routes/AboutUs.jsx": {
    id: "routes/AboutUs";
    page: "/";
  };
  "routes/products.jsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/cart.jsx": {
    id: "routes/cart";
    page: "/cart";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/AboutUs": typeof import("./app/routes/AboutUs.jsx");
  "routes/products": typeof import("./app/routes/products.jsx");
  "routes/cart": typeof import("./app/routes/cart.jsx");
};