// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/cart": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/cart";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
};